controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
      gains:
        joint_1: {p: 100.0, d: 10.0, i: 1.0}
        joint_2: {p: 100.0, d: 10.0, i: 1.0}
        joint_3: {p: 100.0, d: 10.0, i: 1.0}
        joint_4: {p: 100.0, d: 10.0, i: 1.0}
        joint_5: {p: 100.0, d: 10.0, i: 1.0}
        joint_6: {p: 100.0, d: 10.0, i: 1.0}
